In [1]:
import tensorflow as tf

###Learning how tensor dimensions work

In [12]:
tensor_zero_d = tf.constant([1])
print(tensor_zero_d)

tf.Tensor([1], shape=(1,), dtype=int32)


In [14]:
tensor_one_d = tf.constant([1,2])
print(tensor_one_d)

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [13]:
tensor_two_d = tf.constant([
  [1,2,3,4],
  [5,6,7,8]
])
print(tensor_two_d)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [17]:
tensor_three_d = tf.constant([
    [[1,2,3,4],
    [5,6,7,8]],
    [[-1,4,-6,0],
     [3,1,5,-2]],
    [[-2,6,-1,5],
     [2,7,8,-9]]
])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[-1  4 -6  0]
  [ 3  1  5 -2]]

 [[-2  6 -1  5]
  [ 2  7  8 -9]]], shape=(3, 2, 4), dtype=int32)


In [19]:
tensor_four_d = tf.constant([
    [[[1,2,3,4],
    [5,6,7,8]],
    [[-1,4,-6,0],
     [3,1,5,-2]],
    [[-2,6,-1,5],
     [2,7,8,-9]]],
    [[[5,2,4,4],
    [1,63,72,8]],
    [[-15,41,-64,0],
     [3,1,5,-2]],
    [[-2,6,-1,5],
     [2,7,8,-9]]],


])
print(tensor_four_d)

tf.Tensor(
[[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[-1  4 -6  0]
   [ 3  1  5 -2]]

  [[-2  6 -1  5]
   [ 2  7  8 -9]]]


 [[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[-1  4 -6  0]
   [ 3  1  5 -2]]

  [[-2  6 -1  5]
   [ 2  7  8 -9]]]], shape=(2, 3, 2, 4), dtype=int32)


### Casting Tenors

In [26]:
#Code below errors cause, in some cases, you can't cast without tf.cast
#tensor_one_d = tf.constant([2,0.,-5,75], dtype=tf.int16)
#How to properly cast
tensor_one_d = tf.constant([2,0.,-5,75], dtype=tf.float32)
casted_int_tensor = tf.cast(tensor_one_d, dtype = tf.int16)
casted_bool_tensor = tf.cast(tensor_one_d, dtype = tf.bool)
print(casted_int_tensor)
print(casted_bool_tensor)

tf.Tensor([ 2  0 -5 75], shape=(4,), dtype=int16)
tf.Tensor([ True False  True  True], shape=(4,), dtype=bool)
