<a href="https://colab.research.google.com/github/JosephSAlemu/LearningStuff/blob/Learning-Tensors/CV_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

###Learning how tensor dimensions work

In [ ]:
tensor_zero_d = tf.constant([1])
print(tensor_zero_d)
print(tensor_zero_d.shape)

tf.Tensor([1], shape=(1,), dtype=int32)
(1,)


In [ ]:
tensor_one_d = tf.constant([1,2])
print(tensor_one_d)

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
  [1,2,3,4],
  [5,6,7,8]
])
print(tensor_two_d)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
    [[1,2,3,4],
    [5,6,7,8]],
    [[-1,4,-6,0],
     [3,1,5,-2]],
    [[-2,6,-1,5],
     [2,7,8,-9]]
])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[-1  4 -6  0]
  [ 3  1  5 -2]]

 [[-2  6 -1  5]
  [ 2  7  8 -9]]], shape=(3, 2, 4), dtype=int32)


In [ ]:
tensor_four_d = tf.constant([
    [[[1,2,3,4],
    [5,6,7,8]],
    [[-1,4,-6,0],
     [3,1,5,-2]],
    [[-2,6,-1,5],
     [2,7,8,-9]]],
    [[[5,2,4,4],
    [1,63,72,8]],
    [[-15,41,-64,0],
     [3,1,5,-2]],
    [[-2,6,-1,5],
     [2,7,8,-9]]],


])
print(tensor_four_d)

tf.Tensor(
[[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[-1  4 -6  0]
   [ 3  1  5 -2]]

  [[-2  6 -1  5]
   [ 2  7  8 -9]]]


 [[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[-1  4 -6  0]
   [ 3  1  5 -2]]

  [[-2  6 -1  5]
   [ 2  7  8 -9]]]], shape=(2, 3, 2, 4), dtype=int32)


### Casting Tenors

In [ ]:
#Code below errors cause, in some cases, you can't cast without tf.cast
#tensor_one_d = tf.constant([2,0.,-5,75], dtype=tf.int16)
#How to properly cast
tensor_one_d = tf.constant([2,0.,-5,75], dtype=tf.float32)
casted_int_tensor = tf.cast(tensor_one_d, dtype = tf.int16)
casted_bool_tensor = tf.cast(tensor_one_d, dtype = tf.bool)
print(tensor_one_d)
print(casted_int_tensor)
print(casted_bool_tensor)

tf.Tensor([ 2.  0. -5. 75.], shape=(4,), dtype=float32)
tf.Tensor([ 2  0 -5 75], shape=(4,), dtype=int16)
tf.Tensor([ True False  True  True], shape=(4,), dtype=bool)


## Numpy

In [ ]:
import numpy as np

In [ ]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [ ]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


## Fills and Shapes

In [ ]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)

print(eye_tensor)
print(3*eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)


In [ ]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=2,
    batch_shape=[2,4,],
    dtype=tf.dtypes.float32,
    name=None
)

print(eye_tensor)

tf.Tensor(
[[[[1. 0.]
   [0. 1.]
   [0. 0.]]

  [[1. 0.]
   [0. 1.]
   [0. 0.]]

  [[1. 0.]
   [0. 1.]
   [0. 0.]]

  [[1. 0.]
   [0. 1.]
   [0. 0.]]]


 [[[1. 0.]
   [0. 1.]
   [0. 0.]]

  [[1. 0.]
   [0. 1.]
   [0. 0.]]

  [[1. 0.]
   [0. 1.]
   [0. 0.]]

  [[1. 0.]
   [0. 1.]
   [0. 0.]]]], shape=(2, 4, 3, 2), dtype=float32)


In [ ]:
#Fils tensor shape of choice with any value
fill_tensor = tf.fill(
    [3,4],
    5,
    name=None
)
print(fill_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [ ]:
#Fills tensor shape of choice with ones
fill_tensor_one = tf.ones(
    [5,3,2],
    dtype=tf.dtypes.float32,
    name=None
)
tf_cast = tf.c
print(fill_tensor_one)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(5, 3, 2), dtype=float32)


In [ ]:
fill_tensor_zero = tf.zeros(
    [4,2],
    dtype=tf.dtypes.float32,
    name=None
)
print(fill_tensor_zero)
tf_cast_zero = tf.cast(fill_tensor_zero, dtype=tf.dtypes.bool)
print(tf_cast_zero)

tf.Tensor(
[[False False]
 [False False]
 [False False]
 [False False]], shape=(4, 2), dtype=bool)
tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]], shape=(4, 2), dtype=float32)


In [ ]:
#Creates tensor with shape of input but replace vals with one
tensor_ones_like= tf.ones_like(fill_tensor)
print(tensor_ones_like)

tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(3, 4), dtype=int32)


In [ ]:
print(tf.shape(tensor_ones_like))

tf.Tensor([3 4], shape=(2,), dtype=int32)
